---
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
    exclude_paths:
    - public/
    - vendor/
  fixme:
    enabled: true
    exclude_patterns:
    - ".rubocop_enabled.yml"
    - ".rubocop.yml"
  rubocop:
    enabled: true
    config: ".rubocop.yml"
    checks:
      Rubocop/Style/RedundantReturn:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 20

ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.js"
exclude_paths:
- public/assets/
- db/
- spec/
- config/