version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/circleci-dir
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
      - image: postgres:9.5-alpine
        environment:
          POSTGRES_USER: restomap
          POSTGRES_DB: test_restomap
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Bundle Install
          command: bundle check || bundle install
      
      # Store bundle cache
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      # Database setup
      - run:
          name: Database setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
            bundle exec rake db:schema:load